url: https://capixaba.dev.br # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog


title: Capixaba Dev # the name of your site, e.g. ACME Corp.
lang: pt-br
tagline: Blog de programação, Linux e tecnologia em geral
description: > # this means to ignore newlines until "show_excerpts:"
  Blog de programação, Linux e tecnologia em geral


author:
  name: Capixaba DEV


minima:
  date_format: "%-d, %b %Y"
  social_links:
    github:  capixabadev
    telegram: capixabadev


google_analytics: UA-163210642-1
show_excerpts: true
permalink: /:title/


disqus:
    shortname: douglasgusson-github-io


sass:
  style: compressed


paginate: 5
paginate_path: "/:num/"


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
