url: https://capixabadev.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog


title: Capixaba Dev # the name of your site, e.g. ACME Corp.
lang: pt-br
tagline: Blog pessoal sobre programação
description: > # this means to ignore newlines until "show_excerpts:"
  Blog pessoal sobre programação de um desenvolvedor em constante aprendizagem


author:
  name: Douglas Gusson


minima:
  date_format: "%-d, %b %Y"
  social_links:
    github:  douglasgusson
    telegram: douglasgusson
    youtube: douglasgusson
    instagram: gussond
    linkedin: douglasgusson


google_analytics: UA-163210642-1
show_excerpts: true
permalink: /:title/


disqus:
    shortname: douglasgusson-github-io


sass:
  style: compressed


paginate: 5
paginate_path: "/:num/"


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
